- shell:
      - command: |
            sudo docker run -d --restart unless-stopped --name duckdns -e TZ=Europe/Prague \
            -e SUBDOMAINS="$(cat ""${PWD}"/../secrets/duck_subdomains")" -e TOKEN="$(cat ""${PWD}"/../secrets/duck_token")" \
            ghcr.io/linuxserver/duckdns
        stdout: true
        stdin: true
        stderr: true
