- sudo:
      - link:
            /etc/systemd/system/monitor.reset.service: scripts/monitor.reset.service
      - shell:
            - systemctl enable monitor.reset
            - systemctl start monitor.reset
