default_config:

tts:
  - platform: google_translate

zone:
  - name: Med. School
    latitude: 50.146600
    longitude: 14.098480
    radius: 60
    icon: mdi:school
  - name: Hospital
    latitude: 50.141024
    longitude: 14.087848
    radius: 135
    icon: mdi:briefcase
  - name: CVUT
    latitude: 50.102836
    longitude: 14.391640
    radius: 400
    icon: mdi:school
  - name: ABRA
    latitude: 50.042861
    longitude: 14.314760
    radius: 100
    icon: mdi:briefcase
  - name: Airport
    latitude: 50.102309
    longitude: 14.267545
    radius: 1480
    icon: mdi:briefcase

sensor:
  - platform: mitemp_bt
    mac: '58:2D:34:37:2B:96'
    name: Bedroom TH
  - platform: mitemp_bt
    mac: '58:2D:34:38:37:70'
    name: Outdoor TH
  - platform: template
    sensors:
      sunset_time:
        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting)  | timestamp_custom("%H:%M") }}'
      sunrise_time:
        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising)  | timestamp_custom("%H:%M") }}'

sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password

light:
  - platform: flux_led
    devices:
      192.168.0.171:
        name: Bedroom Lamp
        mode: rgbw
      192.168.0.174:
        name: Ambient Light
        mode: rgb

media_player:
#  - platform: xboxone
#    ip_address: 192.168.0.160
#    device: FD00D4D2889E1428
#    name: Xbox One
#    authentication: false

cast:
  media_player:
    - host: 192.168.0.162
    - host: 192.168.0.163
    - host: 192.168.0.164

remote:
  - platform: harmony
    name: Harmony Hub
    host: 192.168.0.166

device_tracker:
  - platform: google_maps
    username: !secret gm_username
  - platform: ping
    hosts: 
      pc_daniel: 192.168.0.150
      xbox: 192.168.0.160
      samsung_tv: 192.168.0.161
      phone_daniel: 192.168.0.169
      phone_miroslava: 192.168.0.199
      phone_tereza: 192.168.0.198

switch:
  - platform: template
    switches:
      pc:
        friendly_name: PC
        value_template: "{{ is_state('device_tracker.pc_daniel', 'home') }}"
        turn_on:
          service: script.pc_on
        turn_off:
          service: script.pc_off
      samsung_tv:
        friendly_name: TV
        value_template: "{{ is_state('device_tracker.samsung_tv', 'home') }}"
        turn_on:
          service: script.tv_on
        turn_off:
          service: script.tv_off
      xbox:
        friendly_name: Xbox One
        value_template: "{{ is_state('device_tracker.xbox', 'home') }}"
        turn_on:
          service: script.xbox_on
        turn_off:
          service: script.xbox_off

shell_command:
  pc_on: 'wakeonlan 34:64:A9:34:A6:69'
  #doesnt work in docker, ssh into host?
  pc_off: !secret pc_off #'net rpc -S 192.168.0.150 -U [username]%[password] shutdown -t 1 -f'

notify:
  - name: Discord
    platform: discord
    token: !secret discord_token

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
