default_config:

tts:
    - platform: google_translate

light:
    - platform: flux_led
      devices:
          192.168.0.174:
              name: Ambient Light
              mode: rgb
          192.168.175:
              name: Ambient Light 2
              mode: rgb

# only from UI for some reason
#remote:
#    - platform: harmony
#      name: Harmony Hub
#      host: 192.168.0.166

device_tracker:
    - platform: ping
      hosts:
          pc: 192.168.0.150
          xbox: 192.168.0.160
          tv: 192.168.0.161
          phone: 192.168.0.169

switch:
    - platform: template
      switches:
          pc:
              friendly_name: PC
              value_template: "{{ is_state('device_tracker.pc', 'home') }}"
              turn_on:
                  service: script.pc_on
              turn_off:
                  service: script.pc_off
          tv:
              friendly_name: TV
              value_template: "{{ is_state('device_tracker.tv', 'home') }}"
              turn_on:
                  service: script.tv_on
              turn_off:
                  service: script.tv_off
          xbox:
              friendly_name: Xbox
              value_template: "{{ is_state('device_tracker.xbox', 'home') }}"
              turn_on:
                  service: script.xbox_on
              turn_off:
                  service: script.xbox_off
          receiver:
              friendly_name: Receiver
              value_template: "{{ is_state('device_tracker.tv', 'home') }}"
              turn_on:
                  service: script.receiver_on
              turn_off:
                  service: script.receiver_off

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
